---
  - name: Nginx Setup
    hosts: skoleserver
    become: true
    tasks:
      - name: Update and Upgrade
        apt:
          upgrade: yes
          update_cache: yes
        
      - name: Ensure NGINX is installed
        apt: 
          name: nginx
          state: latest
        
      - name: Change Nginx Config
        ansible.builtin.copy:
          src: /Users/chw/Desktop/Dev/AnsibleTestingServer/nginxconfig
          dest: /etc/nginx/sites-available/default
          owner: root
          group: root
          mode: '0644'           

      - name: Verify Nginx Config
        command: "nginx -t"
        
      - name: Create new index.html file
        ansible.builtin.copy:
          src: /Users/chw/Desktop/Dev/AnsibleTestingServer/index.html
          dest: /var/www/html/index.html

      - name: Delete normal nginx file
        ansible.builtin.file:
          state: absent
          path: /var/www/html/index.nginx-debian.html

      - name: Restart Nginx Systemctl
        command: "systemctl restart nginx"