---
  - name: Secure Ubuntu
    hosts: skoleserver
    become: true
    tasks:
      - name: Update and Upgrade
        ansible.builtin.package:
          upgrade: yes
          update_cache: yes

      - name: Ensure fail2ban is installed
        ansible.builtin.package:
          name: fail2ban
          state: latest

      - name: Ensure ufw is installed
        ansible.builtin.package:
          name: ufw
          state: latest

      - name: Disable incoming by default UFW
        ufw:
          default: deny
          direction: incoming
          state: enabled

      - name: Disable outgoing by default UFW
        ufw:
          default: deny
          direction: outgoing
          state: enabled

      - name: Allow outbound HTTP (TCP/80)
        ufw:
          rule: allow
          direction: out
          proto: tcp
          port: 80
          comment: "Allow outbound HTTP traffic"

      - name: Allow outbound HTTPS (TCP/443)
        ufw:
          rule: allow
          direction: out
          proto: tcp
          port: 443
          comment: "Allow outbound HTTPS traffic"

      - name: Allow outbound DNS (UDP/53)
        ufw:
          rule: allow
          direction: out
          proto: udp
          port: 53
          comment: "Allow outbound DNS queries"

      - name: Allow outbound NTP (UDP/123)
        ufw:
          rule: allow
          direction: out
          proto: udp
          port: 123
          comment: "Allow outbound NTP time sync"

      - name: Allow inbound SSH (TCP/22)
        ufw:
          rule: allow
          direction: in
          proto: tcp
          port: 22
          comment: "Allow inbound SSH connections"

      - name: Enable UFW
        ufw:
          state: enabled
          logging: on

      - name: Ensure SSH config directory exists
        file:
          path: /etc/ssh/sshd_config.d
          state: directory
          mode: '0755'

      - name: Check if 50-cloud-init.conf exists
        stat:
          path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        register: conf_file

      - name: Create 50-cloud-init.conf if it doesn't exist
        file:
          path: /etc/ssh/sshd_config.d/50-cloud-init.conf
          state: touch
          mode: '0600'
        when: not conf_file.stat.exists

      - name: Configure SSH Password Authentication
        lineinfile:
          path: /etc/ssh/sshd_config.d/50-cloud-init.conf
          regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication no'
          validate: '/usr/sbin/sshd -t -f %s'

      - name: Configure SSH Pubkey Authentication
        lineinfile:
          path: /etc/ssh/sshd_config.d/50-cloud-init.conf
          regexp: '^PubkeyAuthentication'
          line: 'PubkeyAuthentication yes'
          validate: '/usr/sbin/sshd -t -f %s'

      - name: Disable Root Login
        lineinfile:
          path: /etc/ssh/sshd_config.d/50-cloud-init.conf
          regexp: '^PermitRootLogin'
          line: 'PermitRootLogin no'
          validate: '/usr/sbin/sshd -t -f %s'

      - name: Restart SSH service
        service:
          name: sshd
          state: restarted